apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: necoperf-cli-service-discovery
  namespace: necoperf
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: necoperf-cli
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
