apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: necoperf-cli-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: necoperf-cli
subjects:
  - kind: ServiceAccount
    name: necoperf-cli
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: necoperf-cli-service-discovery-binding
  namespace: necoperf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: necoperf-cli-service-discovery
subjects:
  - kind: ServiceAccount
    name: necoperf-cli
    namespace: default
