apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: necoperf-daemon
  namespace: necoperf
  labels:
    k8s-app: necoperf-daemon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: necoperf-daemon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: necoperf-daemon
    spec:
      hostPID: true
      terminationGracePeriodSeconds: 30
      containers:
        - name: necoperf-daemon
          image: necoperf-daemon:dev
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - SYSLOG
                - SYS_PTRACE
                - PERFMON
                - SYS_CHROOT
                - SYS_ADMIN
              drop:
                - ALL
          volumeMounts:
            - name: necoperf-workdir
              mountPath: /var/necoperf
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
            - name: sys-kernel-tracing
              mountPath: /sys/kernel/tracing
          ports:
            - name: grpc
              containerPort: 6543
            - name: metrics
              containerPort: 6541
          livenessProbe:
            grpc:
              port: 6543
            initialDelaySeconds: 10
          readinessProbe:
            grpc:
              port: 6543
            initialDelaySeconds: 5
      volumes:
        - name: necoperf-workdir
          emptyDir: {}
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
        - name: sys-kernel-tracing
          hostPath:
            path: /sys/kernel/tracing
