apiVersion: v1
kind: Pod
metadata:
  name: necoperf-client
  namespace: default
spec:
  containers:
    - name: necoperf-client
      image: necoperf-cli:dev
      imagePullPolicy: IfNotPresent
      command: ["pause"]
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
  serviceAccountName: necoperf-cli
