[book]
language = "en"
multilingual = false
src = "."
title = "KubeIntrospection Documentation"

[output.html]
git-repository-url = "https://github.com/cybozu-go/kubeintrospection"
edit-url-template = "https://github.com/cybozu-go/kubeintrospection/edit/main/docs/{path}"
site-url = "/kubeintrospection/"
