[book]
language = "en"
multilingual = false
src = "."
title = "NecoPerf Documentation"

[output.html]
git-repository-url = "https://github.com/cybozu-go/necoperf"
edit-url-template = "https://github.com/cybozu-go/necoperf/edit/main/docs/{path}"
site-url = "/necoperf/"
